SELECT
  *
FROM
  "TV"."BRIGHT"."VIEWERSHIP"
LIMIT
  10;

  SELECT
  *
FROM
  "TV"."BRIGHT"."USERPROFILE"
LIMIT
  10;
  
SELECT  A.USERID,
        A.NAME,
        SURNAME,
        EMAIL,
        GENDER,
        RACE,
        AGE,
        PROVINCE,
        SOCIAL_MEDIA_HANDLE,
        CHANNEL2,
        RECORDDATE2,
        DURATION_2
FROM   "TV"."BRIGHT"."USERPROFILE" AS A
FULL OUTER JOIN "TV"."BRIGHT"."VIEWERSHIP" AS B
ON A.USERID=B."UserID";

SELECT USERID,NAME,SURNAME,EMAIL,GENDER, RACE,AGE,PROVINCE,SOCIAL_MEDIA_HANDLE,
FROM "TV"."BRIGHT"."USERPROFILE"
UNION
SELECT userid,CHANNEL2,RECORDDATE2,DURATION_2
FROM "TV"."BRIGHT"."VIEWERSHIP";

SELECT  
    A.USERID,
    A.NAME,
    A.SURNAME,
    A.EMAIL,
    A.GENDER,
    A.RACE,
    A.AGE,
    CASE
        WHEN AGE BETWEEN '0' AND'0' THEN 'NotSpecified'
        WHEN AGE BETWEEN '1' AND '11' THEN 'Children'
        WHEN AGE BETWEEN '12' AND '19' THEN 'Teenager'
        WHEN AGE BETWEEN '20' AND '35' THEN 'YoungAdult'
        WHEN AGE BETWEEN '36' AND '60' THEN 'Adult'
        ELSE 'Elderly'
    END AS AGE_BUCKET,
    A.PROVINCE,
    A.SOCIAL_MEDIA_HANDLE,
    B.CHANNEL2,
    B.RECORDDATE3,
    TO_CHAR(TO_DATE(B.RECORDDATE3, 'MM/DD/YYYY HH24:MI'), 'YYYYMM') AS MONTH_WATCHED,
    TO_CHAR(TO_TIMESTAMP(B.RECORDDATE3, 'MM/DD/YYYY HH24:MI'), 'HH24:MI') AS TIME_STAMP,
    CASE
     WHEN MONTH_WATCHED ='201601'THEN 'January'
     WHEN MONTH_WATCHED ='201602'THEN 'February'
     WHEN MONTH_WATCHED ='201603'THEN 'March'
     ELSE 'InBetween'
    END AS WATCHED_MONTH,
    CASE
        WHEN TIME_STAMP BETWEEN '00:00' AND '05:59' THEN 'Midnight'
        WHEN TIME_STAMP BETWEEN '06:00' AND '11:59' THEN 'Morning'
        WHEN TIME_STAMP BETWEEN '12:00' AND '19:59' THEN 'Day'
        ELSE 'Night'
    END AS TIME_BUCKETS,
    B.DURATION_2,
    CASE
        WHEN B.DURATION_2 BETWEEN '00:00:00' AND '02:59:59' THEN 'Minimum'
        WHEN B.DURATION_2 BETWEEN '03:00:00' AND '05:59:59' THEN 'Average'
        WHEN B.DURATION_2 BETWEEN '06:00:00' AND '08:59:59' THEN 'High'
        ELSE 'Very_High'
    END AS WATCH_TIME
FROM "TV"."BRIGHT"."USERPROFILE" A
FULL OUTER JOIN "TV"."BRIGHT"."VIEWERSHIP1" B
    ON A.USERID = B."UserID";
